digit1=input("enter any number")
digit2=input("enter second number")
a=float(digit1)/float(digit2)
print(a)
b=int(digit1)*int(digit2)
print(b)
c=int(digit1)+int(digit2)
print(c)
d=int(digit1)-int(digit2)
print(d)